# creation numpy N_D arrays

In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
# for two array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4=np.ones((2,3)) #data type float a rahi h
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
identity=np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr7=np.arange(5,10) 
arr7

array([5, 6, 7, 8, 9])

In [11]:
arr8=np.arange(5,10,2) # first starting secong ending and third is step to skip
arr8

array([5, 7, 9])

In [12]:
arr9=np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [13]:
arr10=arr1.copy()
arr10

array([1, 2, 3, 4, 5])

In [15]:
arr1.shape

(5,)

In [16]:
arr2.shape

(2, 3)

In [18]:
arr11=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]]])

In [19]:
arr11.shape

(2, 2, 2)

In [ ]:
arr11.ndim  # dim means dimension

3

In [22]:
# size the number of elements present in bracket
arr11.size

8

In [26]:
arr1.size

5

In [29]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2.dtype

dtype('int64')

In [34]:
arr5.dtype

dtype('float64')

In [ ]:
arr13=arr5.astype("int") # astype ma jo type lilkhy gy wo datatype usi ma convert jo jati h
arr13

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [38]:
arr13.dtype

dtype('int64')