In [1]:
import numpy as np

In [3]:
list1=range(100)
list1

range(0, 100)

In [4]:
arr1=np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
import sys

In [6]:
print(sys.getsizeof(87)*len(list1))

2800


In [7]:
print(arr1.itemsize*arr1.size)

800


In [11]:
arr2=arr1[np.newaxis, :] # it convert into two array
arr2
# arr2=arr1[ : ,np.newaxis] # it convert into two array
# arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [9]:
arr2.shape

(1, 100)

In [15]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [16]:
arr1.shape

(5,)

In [17]:
arr2=np.array([(1,2,3,4,5),(6,7,8,9,0)])
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
q=arr1-arr2 # subtract
q

array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5,  5]])

# addition

In [21]:
# q=arr1+arr2
# q
hi=np.add(arr1,arr2)
hi

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13,  5]])

# same operation as multiplication and division.........

In [18]:
arr6=np.full((2,5),5)
arr6

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])