# Create an empty array

In [24]:
import numpy as np
arr1=np.empty((2,5))
arr1

array([[6.95208749e-310, 0.00000000e+000, 1.27173923e-311,
        2.02369289e-320, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [25]:
print(arr1[1])

[0. 0. 0. 0. 0.]


In [26]:
arr2=np.arange(9)
print(arr2)

[0 1 2 3 4 5 6 7 8]


In [27]:
lin=np.linspace(0,10,num=10)  #10 number print hu gy aur un ka drmyn equal space ho gi
print(lin)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [28]:
# datatype hum sath b bta skty
arr2=np.ones(2,dtype=np.int64) # is tra hum koi b array bna skty
arr2

array([1, 1])

In [29]:
# Sorting
arr=np.array([0,8,5,4,3,2,8])
arr
np.sort(arr)

array([0, 2, 3, 4, 5, 8, 8])

In [30]:
# concentination
a=([1,2,3,4,5])
b=([4,5,6,7,9])
c=np.concat((a,b))
print(c)

[1 2 3 4 5 4 5 6 7 9]


In [31]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
z=np.concatenate((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
z=np.concatenate((x,y),axis=0) # isy axis 1 pa concate nai kr skty in ma size difference h
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
x

array([[1, 2],
       [3, 4]])

In [21]:
y

array([[5, 6]])

In [34]:
x=np.array([[1,2],[3,4]])
u=np.array([[5,6],[7,9]])
m=np.concatenate((x,u),axis=1)
m

array([[1, 2, 5, 6],
       [3, 4, 7, 9]])

In [50]:
array_example=np.array([[[1,2,3,6],
                  [4,5,6,7]],


                 [[1,2,3,8],
                 [4,5,6,0]],

                 
                 [[5,6,7,4],
                 [6,7,8,8]]])
array_example

array([[[1, 2, 3, 6],
        [4, 5, 6, 7]],

       [[1, 2, 3, 8],
        [4, 5, 6, 0]],

       [[5, 6, 7, 4],
        [6, 7, 8, 8]]])

In [51]:
array_example.size

24

In [52]:
array_example.shape

(3, 2, 4)

In [54]:
array_example1=np.array([[[1,2,3,6]],
            
                 [[4,5,6,0]],
                 [[6,7,8,8]]])
array_example1

array([[[1, 2, 3, 6]],

       [[4, 5, 6, 0]],

       [[6, 7, 8, 8]]])

In [57]:
a1=array_example1.reshape(3,2,2)
a1

array([[[1, 2],
        [3, 6]],

       [[4, 5],
        [6, 0]],

       [[6, 7],
        [8, 8]]])

# Indexing and slicing

In [58]:
a2=np.array([1,2,3,4,5,6,7,8])
a2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
a3=a2[2]
print(a3)

3


In [62]:
print(a2[2:5])

[3 4 5]


In [65]:
a2[-4:]

array([5, 6, 7, 8])

In [66]:
a2[-4:-2]

array([5, 6])

In [67]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
b[0]

array([1, 2, 3])

In [69]:
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
b[b<5]  
# write any operation

array([1, 2, 3, 4])

In [71]:
b[(b<5)&(b<2)]

array([1])

In [2]:
import numpy as np

In [ ]:
a=np.array([1,2,3,2])
a

array([1, 2, 3, 4])

# reshape

In [ ]:
a=np.arange(1,11).reshape(5,2)  # reshape krny ka liy jo 2 number diy jaty hain un ka product un element ka equal hona zaruri h jo elements list ma present hoty
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# randomly array generate krna

In [ ]:
np.random.random((3,4))   

array([[0.50024675, 0.71891327, 0.66348385, 0.56589612],
       [0.31412134, 0.12770084, 0.35355176, 0.36853236],
       [0.17251808, 0.63436942, 0.64850066, 0.54502515]])

# changing datatype

In [22]:
a3=np.array([1,2,3,4,5,6])
a3

array([1, 2, 3, 4, 5, 6])

In [24]:
a3.dtype

dtype('int64')

In [28]:
# astype
a3.astype(np.int32)

array([1, 2, 3, 4, 5, 6], dtype=int32)

# Array operation


In [32]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Arthmetic operation
a1**2
# a1+2
# a1*2
# Any operation

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [31]:
# relational operator
a1>6

array([[False, False, False, False, False],
       [False, False,  True,  True,  True]])

# vector operation

In [ ]:
a1+a2 # items dono array ma equal hona zaruri hota

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [34]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Array functions

In [40]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[62., 42., 60.],
       [66., 75., 58.],
       [ 4., 17., 50.]])

In [ ]:
np.sum(a1)  # same min,max,product funtion work

np.float64(434.0)

In [ ]:
# agr ak row ka max, min element find krna ho to
np.max(a1,axis=1) # 1 for rwos and 0 for columns

array([62., 75., 50.])

In [ ]:
#mean,medain,std,var
np.mean(a1) # 3 is ma b axis 0 ya axis 1 kr skty

np.float64(48.22222222222222)

# dot product

In [ ]:
a1=np.random.random((3,4))
a2=np.random.random((4,3)) # dot product ma frist ka column second ki rows ka equal hony chahiy

In [46]:
np.dot(a1,a2)

array([[1.53149385, 0.4622183 , 1.84202684],
       [1.55205718, 1.07818285, 2.0065154 ],
       [0.88714279, 0.37466833, 1.27715783]])

In [ ]:
# log and exponent function
np.log(a1)
# np.exp(a1)

array([[-0.24804166, -1.52483674, -0.97880675, -0.01273633],
       [-0.17164472, -0.1519291 , -0.05878126, -1.44536203],
       [-3.52691276, -0.74037102, -1.20459759, -0.18010493]])

# slicing

In [52]:
a1=np.arange(12).reshape((3,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[2,3]  # phly rwo phir column btana

np.int64(11)

In [55]:
a3=np.arange(8).reshape((2,2,2))
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[0,1,0] # phly btana h ka kon c 2D array h phir row phir column lakin indrx 0 sa start hona

np.int64(2)

In [59]:
# slicing
a1[:,2]

array([ 2,  6, 10])

# Iteration

In [ ]:
for i in a3: # same for 1d 2D and 3d
    print(i)


[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
# tranpose funtion reshape ki tra likha jataa aur ravel b ravel jitni b zyada Dimension ka array ho usy 1d ma convert kr deta h

# Fancy indexing

In [2]:
import numpy as np

In [3]:
a1=np.arange(24).reshape((6,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a1[:,[1,2,3]]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [9]:
a1[[0,2,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23]])